// Placeholder sponsored ads — shown when no real ads exist in the database.
// Rotate through ski / outdoor brands relevant to Utah students.
export const FAKE_ADS = [
  {
    id: 'fake-burton',
    company_name: 'Burton Snowboards',
    tagline: 'The world\'s best snowboards, boots, bindings & outerwear. Student discount available — 20% off with your .edu email.',
    website_url: 'https://www.burton.com',
    cta: 'Shop Burton →',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    emoji: '🏂',
    accent: '#e94560',
  },
  {
    id: 'fake-salomon',
    company_name: 'Salomon',
    tagline: 'Premium skis, boots & gear engineered for the mountain. Gear up for the season at a Utah retailer near you.',
    website_url: 'https://www.salomon.com',
    cta: 'Find Your Gear →',
    gradient: 'linear-gradient(135deg, #0d1b2a 0%, #1b4332 100%)',
    emoji: '⛷️',
    accent: '#40916c',
  },
  {
    id: 'fake-snowbird',
    company_name: 'Snowbird',
    tagline: 'The Greatest Snow on Earth™ is right in your backyard. Season passes from $649 — student pricing available.',
    website_url: 'https://www.snowbird.com',
    cta: 'Get a Pass →',
    gradient: 'linear-gradient(135deg, #c0392b 0%, #96281b 100%)',
    emoji: '🦅',
    accent: '#f5cba7',
  },
  {
    id: 'fake-smith',
    company_name: 'Smith Optics',
    tagline: 'Born in Sun Valley. Built for the mountain. ChromaPop lenses for peak-to-peak clarity — student deals inside.',
    website_url: 'https://www.smithoptics.com',
    cta: 'Shop Goggles →',
    gradient: 'linear-gradient(135deg, #f39c12 0%, #d35400 100%)',
    emoji: '🕶️',
    accent: '#fff',
  },
  {
    id: 'fake-alta',
    company_name: 'Alta Ski Area',
    tagline: 'Skiers only since 1939. 500+ inches of powder annually. Grab a student lift ticket and hit the best terrain in Utah.',
    website_url: 'https://www.alta.com',
    cta: 'Buy Tickets →',
    gradient: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)',
    emoji: '🏔️',
    accent: '#ecf0f1',
  },
  {
    id: 'fake-dakine',
    company_name: 'Dakine',
    tagline: 'Bags, outerwear & snow accessories built for the mountain lifestyle. Free shipping on orders over $50.',
    website_url: 'https://www.dakine.com',
    cta: 'Explore Dakine →',
    gradient: 'linear-gradient(135deg, #005f73 0%, #0a9396 100%)',
    emoji: '🎒',
    accent: '#94d2bd',
  },
]
