export const SCHOOLS = [
  {
    id: 'utah',
    name: 'University of Utah',
    shortName: 'U of U',
    primary: '#CC0000',
    light: '#e53e3e',
    dark: '#9b0000',
    gradient: 'linear-gradient(135deg, #CC0000, #ff6b6b)',
    live: true,
  },
  {
    id: 'tcu',
    name: 'Texas Christian University',
    shortName: 'TCU',
    primary: '#4D1979',
    light: '#7c3aed',
    dark: '#2d0f47',
    gradient: 'linear-gradient(135deg, #4D1979, #7c3aed)',
    live: true,
  },
  {
    id: 'byu',
    name: 'Brigham Young University',
    shortName: 'BYU',
    primary: '#002E5D',
    light: '#0052a5',
    dark: '#001a35',
    gradient: 'linear-gradient(135deg, #002E5D, #0052a5)',
    live: false,
  },
  {
    id: 'usc',
    name: 'University of Southern California',
    shortName: 'USC',
    primary: '#990000',
    light: '#cc0000',
    dark: '#660000',
    gradient: 'linear-gradient(135deg, #990000, #FFCC00)',
    live: false,
  },
  {
    id: 'unc',
    name: 'UNC Chapel Hill',
    shortName: 'UNC',
    primary: '#4B9CD3',
    light: '#7ab8e8',
    dark: '#2272a5',
    gradient: 'linear-gradient(135deg, #4B9CD3, #13294B)',
    live: false,
  },
  {
    id: 'arizona',
    name: 'University of Arizona',
    shortName: 'UA',
    primary: '#CC0033',
    light: '#e53e5e',
    dark: '#990022',
    gradient: 'linear-gradient(135deg, #CC0033, #003366)',
    live: false,
  },
]

export const getSchoolById = (id) => SCHOOLS.find((s) => s.id === id) ?? null
